# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      oga_no:
        description: 'Boat OGA No'
        default: '315'
        required: true
jobs:
  boat_job:
    runs-on: ubuntu-latest
    name: A job to get a boat
    steps:
    - name: get boat action step
      id: boat
      uses: ogauk/boat@v1.5
      with:
        oga-no: ${{ github.event.inputs.oga_no }}
    - name: Get the output data
      run: echo "the data is ${{ steps.boat.outputs.boat }}"
